/**
 * 
 * Mapped to security Table
 * 
 */
"use strict";

var BasicEntity = require('entity/base/BasicEntity');
var basicEntity = new BasicEntity();

var _ = require('lodash');

var Security = {
		//autogenerated
		id : null,
		//mandatory
		name : null,
		// from four statues Approved, Draft, Not-Active, Waiting for Approval
		status : 0,
		communityModelled : null,
		description : null,
		ownerUserId : null,
		scope : null,
		// default is 0
		dynamicModel : 0,
		isDeleted : null,
		isSubsitutedForPortfolio : 0
}

module.exports = function(){
	_.assign(this, Security, basicEntity);
}
