/**
 * These code will be used by service to send error code controller
 */
module.exports = {
	SUCCESS: 'SUCCESS',
	CREATED: 'CREATED',
	BAD_REQUEST: 'BAD_REQUEST',
	UNAUTHORIZED: 'UNAUTHORIZED',
	FORBIDDEN: 'FORBIDDEN',
	NOT_FOUND: 'NOT_FOUND',
	UNPROCESSABLE: 'UNPROCESSABLE',
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
	IMPORTED: 'IMPORTED',
	ALREADY_DELETED: 'ALREADY_DELETED',
	EXISTS: 'EXISTS',
	NOT_IMPLEMENTED: 'NOT_IMPLEMENTED'
};