/* Defines the team entity */
export interface IUser {
    id: number,
    userName: string,
    status: number,
    createdOn: Date,
    isDeleted: number,
    roleId: number,
    roleType: string,
    roleStatus: string,
    //role: IRole,
    //teams: ITeam[],
    firmId: number,
    firmName: string,
    startDate: Date,
    expireDate: Date,
    name:string,
    email:string,
    strategistId: number,
    strategistName: string,
    loginUserName: string,
    loginUserId: string,
    userId: number,
    //eclipseDbId : number,
    orionConnectExternalId:number,
    eclipseDatabaseId:number,
    eclipseDatabaseName: string,
    url : string
}
